# Generated by Django 2.2.3 on 2019-07-29 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airplanes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='airplane',
            name='model',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
