# Generated by Django 2.2.3 on 2019-07-30 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airplanes', '0002_airplane_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='airplane',
            name='wingspan',
            field=models.IntegerField(null=True),
        ),
    ]
