# Generated by Django 2.2.3 on 2019-07-30 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airplanes', '0003_airplane_wingspan'),
    ]

    operations = [
        migrations.AddField(
            model_name='airplane',
            name='url',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
