# Generated by Django 2.2.3 on 2019-08-02 15:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rocketleague', '0002_auto_20190307_1702'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='referee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
