# Generated by Django 2.2.3 on 2019-08-02 15:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rocketleague', '0003_game_referee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='referee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
