# Generated by Django 2.2.3 on 2019-07-29 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airplanes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='airplane',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
