# Generated by Django 2.2.3 on 2019-08-03 02:47

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('airplanes', '0003_airplane_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='airplane',
            name='wingspan',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='airplane',
            name='url',
            field=models.CharField(max_length=255, null=True, validators=[django.core.validators.URLValidator]),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=255)),
                ('airplane', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='airplanes.Airplane')),
            ],
        ),
    ]
