# Generated by Django 2.2.3 on 2019-07-26 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_auto_20190726_1550'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='note',
            new_name='notes',
        ),
    ]
